#!/usr/bin/env tsx
/**
 * Interactive first-run setup for Clawssify.
 * Checks if .env is configured, and if not, walks the user through setup.
 * Supports Claude/OpenAI subscriptions (via CLIProxyAPI), API keys, and OpenAI-compatible proxies.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { createInterface } from 'node:readline'

const ENV_PATH = resolve(process.cwd(), '.env')

function readEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) return {}
  const content = readFileSync(ENV_PATH, 'utf-8')
  const env: Record<string, string> = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIndex = trimmed.indexOf('=')
    if (eqIndex === -1) continue
    const key = trimmed.slice(0, eqIndex)
    const value = trimmed.slice(eqIndex + 1)
    env[key] = value
  }
  return env
}

function writeEnv(env: Record<string, string>): void {
  const lines = [
    '# Clawssify configuration',
    '# Generated by `pnpm dev` setup wizard',
    '',
  ]
  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}=${value}`)
  }
  writeFileSync(ENV_PATH, lines.join('\n') + '\n', 'utf-8')
}

function hasProxyCredentials(dataDir: string): boolean {
  const authDir = resolve(dataDir, '.proxy', 'auth', '.cli-proxy-api')
  try {
    const files = readdirSync(authDir)
    return files.some((f: string) => f.endsWith('.json'))
  } catch {
    return false
  }
}

function isConfigured(env: Record<string, string>): boolean {
  if (!env.API_KEY || env.API_KEY === 'your-secret-api-key') return false
  if (!env.AI_PROVIDER) return false

  if (env.AI_AUTH_METHOD === 'oauth') {
    return hasProxyCredentials(resolve(env.DATA_DIR || './data'))
  }

  if (!env.AI_API_KEY) return false
  return true
}

async function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()))
  })
}

async function choose(
  rl: ReturnType<typeof createInterface>,
  question: string,
  options: string[],
): Promise<number> {
  console.log(`\n${question}`)
  for (let i = 0; i < options.length; i++) {
    console.log(`  ${i + 1}) ${options[i]}`)
  }
  while (true) {
    const answer = await ask(rl, `\nChoice [1-${options.length}]: `)
    const num = parseInt(answer, 10)
    if (num >= 1 && num <= options.length) return num - 1
    console.log('Invalid choice, try again.')
  }
}

function generateApiKey(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
  let key = 'clw_'
  for (let i = 0; i < 24; i++) {
    key += chars[Math.floor(Math.random() * chars.length)]
  }
  return key
}

async function runSetup(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout })

  console.log('')
  console.log('  ╔═══════════════════════════════════════╗')
  console.log('  ║         Clawssify Setup Wizard        ║')
  console.log('  ║   Claw. Classify. Clarify.            ║')
  console.log('  ╚═══════════════════════════════════════╝')
  console.log('')

  const env: Record<string, string> = {
    PORT: '3000',
    DATA_DIR: './data',
  }

  // 1. Choose AI provider
  const providerChoice = await choose(rl, 'Choose your AI provider:', [
    'Anthropic (Claude) — recommended',
    'OpenAI (GPT)',
    'OpenAI-compatible (Ollama, OpenRouter, LM Studio, etc.)',
  ])

  if (providerChoice === 0) {
    env.AI_PROVIDER = 'anthropic'

    const authChoice = await choose(rl, 'Authentication method:', [
      'Claude subscription (Pro/Max) — use your existing subscription, no extra cost',
      'Anthropic API key — pay-per-token from console.anthropic.com',
    ])

    if (authChoice === 0) {
      env.AI_AUTH_METHOD = 'oauth'
      console.log('\n  Setting up CLIProxyAPI for Claude subscription access...')

      try {
        const { ensureProxyBinary, loginProxy } = await import('./services/proxy.js')
        await ensureProxyBinary(resolve(env.DATA_DIR))
        await loginProxy('claude', resolve(env.DATA_DIR))
        console.log('\n  Authentication successful!')
      } catch (err) {
        console.log(`\n  Authentication failed: ${err instanceof Error ? err.message : err}`)
        console.log('  You can retry by running: pnpm setup')
        rl.close()
        process.exit(1)
      }

      const modelChoice = await choose(rl, 'Choose Claude model:', [
        'claude-sonnet-4-5-20250929 — fast, great quality (recommended)',
        'claude-opus-4-6 — most capable, slower',
        'claude-haiku-4-5-20251001 — fastest, cheapest',
      ])
      env.AI_MODEL = ['claude-sonnet-4-5-20250929', 'claude-opus-4-6', 'claude-haiku-4-5-20251001'][modelChoice]
    } else {
      env.AI_AUTH_METHOD = 'api-key'
      env.AI_API_KEY = await ask(rl, '\nAnthopic API key (sk-ant-...): ')
      env.AI_MODEL = 'claude-sonnet-4-5-20250929'
    }
  } else if (providerChoice === 1) {
    env.AI_PROVIDER = 'openai'

    const authChoice = await choose(rl, 'Authentication method:', [
      'ChatGPT subscription (Plus/Pro) — use your existing subscription',
      'OpenAI API key — pay-per-token from platform.openai.com',
    ])

    if (authChoice === 0) {
      env.AI_AUTH_METHOD = 'oauth'
      console.log('\n  Setting up CLIProxyAPI for ChatGPT subscription access...')

      try {
        const { ensureProxyBinary, loginProxy } = await import('./services/proxy.js')
        await ensureProxyBinary(resolve(env.DATA_DIR))
        await loginProxy('codex', resolve(env.DATA_DIR))
        console.log('\n  Authentication successful!')
      } catch (err) {
        console.log(`\n  Authentication failed: ${err instanceof Error ? err.message : err}`)
        rl.close()
        process.exit(1)
      }

      env.AI_MODEL = 'gpt-4o'
    } else {
      env.AI_AUTH_METHOD = 'api-key'
      env.AI_API_KEY = await ask(rl, '\nOpenAI API key (sk-...): ')
      env.AI_MODEL = 'gpt-4o'
    }
  } else {
    env.AI_PROVIDER = 'openai'
    env.AI_AUTH_METHOD = 'api-key'
    env.AI_BASE_URL = await ask(rl, '\nBase URL (e.g., http://localhost:11434/v1): ')
    env.AI_API_KEY = (await ask(rl, 'API key (or "ollama" for Ollama): ')) || 'ollama'
    env.AI_MODEL = await ask(rl, 'Model name (e.g., llama3, mistral): ')
  }

  // 2. Generate server API key
  const apiKey = generateApiKey()
  env.API_KEY = apiKey
  console.log(`\n  Generated API key for your server: ${apiKey}`)
  console.log('  Use this in the Authorization header: Bearer ' + apiKey)

  // 3. Write .env
  writeEnv(env)
  console.log(`\n  Configuration saved to .env`)
  console.log('  Starting Clawssify server...\n')

  rl.close()
}

// Main
const env = readEnv()
if (!isConfigured(env)) {
  if (env.AI_AUTH_METHOD === 'oauth' && env.API_KEY && env.AI_PROVIDER) {
    // .env exists and looks configured, but proxy credentials are missing — just re-login
    console.log('\n  OAuth credentials missing. Running login flow...')
    const { ensureProxyBinary, loginProxy } = await import('./services/proxy.js')
    const dataDir = resolve(env.DATA_DIR || './data')
    await ensureProxyBinary(dataDir)
    const provider = env.AI_PROVIDER === 'anthropic' ? 'claude' : 'codex'
    await loginProxy(provider as 'claude' | 'codex', dataDir)
    console.log('  Authentication successful! Starting server...\n')
  } else {
    await runSetup()
  }
}
